<onlyfor> & template_url were added
breatheco-de/exercise-excuse-generator-python-cli pull request #5
Opened 2024-12-04 18:34 UTC by Lorenagubaira

2025-01-07 21:45 UTC, tommygonzaleza requested changes

2025-01-07 21:45 UTC, tommygonzaleza commented on README.es.md
> +Recomendamos abrir la el `Python boilerplate`, utilizando una herramienta de aprovisionamiento como [Codespaces](https://4geeks.com/lesson/what-is-github-codespaces) (recomendado) o [Gitpod](https://
~la el Python boilerplate~

2025-01-07 21:45 UTC, tommygonzaleza requested changes

2025-01-07 21:45 UTC, tommygonzaleza commented on README.md
> +$ git clone https://github.com/4GeeksAcademy/flask-rest-hello
Here you should show the python hello boilerplate

2025-01-07 22:54 UTC, tommygonzaleza requested changes

2025-01-07 22:54 UTC, tommygonzaleza commented on README.es.md
>  $ python3 app.py
Here is should say main.py

2025-01-07 22:54 UTC, tommygonzaleza commented on learn.json
> +	"template_url": "https://github.com/4GeeksAcademy/flask-rest-hello",
python-hello

2025-01-08 15:42 UTC, alesanchezr approved these changes

2025-01-08 15:42 UTC, merged